/*
Copyright 2022 The Knative Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
	sourcesv1alpha1 "knative.dev/eventing-rabbitmq/pkg/apis/sources/v1alpha1"
)

// RabbitmqSourceLister helps list RabbitmqSources.
// All objects returned here must be treated as read-only.
type RabbitmqSourceLister interface {
	// List lists all RabbitmqSources in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*sourcesv1alpha1.RabbitmqSource, err error)
	// RabbitmqSources returns an object that can list and get RabbitmqSources.
	RabbitmqSources(namespace string) RabbitmqSourceNamespaceLister
	RabbitmqSourceListerExpansion
}

// rabbitmqSourceLister implements the RabbitmqSourceLister interface.
type rabbitmqSourceLister struct {
	listers.ResourceIndexer[*sourcesv1alpha1.RabbitmqSource]
}

// NewRabbitmqSourceLister returns a new RabbitmqSourceLister.
func NewRabbitmqSourceLister(indexer cache.Indexer) RabbitmqSourceLister {
	return &rabbitmqSourceLister{listers.New[*sourcesv1alpha1.RabbitmqSource](indexer, sourcesv1alpha1.Resource("rabbitmqsource"))}
}

// RabbitmqSources returns an object that can list and get RabbitmqSources.
func (s *rabbitmqSourceLister) RabbitmqSources(namespace string) RabbitmqSourceNamespaceLister {
	return rabbitmqSourceNamespaceLister{listers.NewNamespaced[*sourcesv1alpha1.RabbitmqSource](s.ResourceIndexer, namespace)}
}

// RabbitmqSourceNamespaceLister helps list and get RabbitmqSources.
// All objects returned here must be treated as read-only.
type RabbitmqSourceNamespaceLister interface {
	// List lists all RabbitmqSources in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*sourcesv1alpha1.RabbitmqSource, err error)
	// Get retrieves the RabbitmqSource from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*sourcesv1alpha1.RabbitmqSource, error)
	RabbitmqSourceNamespaceListerExpansion
}

// rabbitmqSourceNamespaceLister implements the RabbitmqSourceNamespaceLister
// interface.
type rabbitmqSourceNamespaceLister struct {
	listers.ResourceIndexer[*sourcesv1alpha1.RabbitmqSource]
}
