/*
Copyright 2022 The Knative Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	gentype "k8s.io/client-go/gentype"
	v1alpha1 "knative.dev/eventing-rabbitmq/pkg/apis/sources/v1alpha1"
	sourcesv1alpha1 "knative.dev/eventing-rabbitmq/pkg/client/clientset/versioned/typed/sources/v1alpha1"
)

// fakeRabbitmqSources implements RabbitmqSourceInterface
type fakeRabbitmqSources struct {
	*gentype.FakeClientWithList[*v1alpha1.RabbitmqSource, *v1alpha1.RabbitmqSourceList]
	Fake *FakeSourcesV1alpha1
}

func newFakeRabbitmqSources(fake *FakeSourcesV1alpha1, namespace string) sourcesv1alpha1.RabbitmqSourceInterface {
	return &fakeRabbitmqSources{
		gentype.NewFakeClientWithList[*v1alpha1.RabbitmqSource, *v1alpha1.RabbitmqSourceList](
			fake.Fake,
			namespace,
			v1alpha1.SchemeGroupVersion.WithResource("rabbitmqsources"),
			v1alpha1.SchemeGroupVersion.WithKind("RabbitmqSource"),
			func() *v1alpha1.RabbitmqSource { return &v1alpha1.RabbitmqSource{} },
			func() *v1alpha1.RabbitmqSourceList { return &v1alpha1.RabbitmqSourceList{} },
			func(dst, src *v1alpha1.RabbitmqSourceList) { dst.ListMeta = src.ListMeta },
			func(list *v1alpha1.RabbitmqSourceList) []*v1alpha1.RabbitmqSource {
				return gentype.ToPointerSlice(list.Items)
			},
			func(list *v1alpha1.RabbitmqSourceList, items []*v1alpha1.RabbitmqSource) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
