/*
Copyright 2022 The Knative Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
	sourcesv1alpha1 "knative.dev/eventing-rabbitmq/pkg/apis/sources/v1alpha1"
	scheme "knative.dev/eventing-rabbitmq/pkg/client/clientset/versioned/scheme"
)

// RabbitmqSourcesGetter has a method to return a RabbitmqSourceInterface.
// A group's client should implement this interface.
type RabbitmqSourcesGetter interface {
	RabbitmqSources(namespace string) RabbitmqSourceInterface
}

// RabbitmqSourceInterface has methods to work with RabbitmqSource resources.
type RabbitmqSourceInterface interface {
	Create(ctx context.Context, rabbitmqSource *sourcesv1alpha1.RabbitmqSource, opts v1.CreateOptions) (*sourcesv1alpha1.RabbitmqSource, error)
	Update(ctx context.Context, rabbitmqSource *sourcesv1alpha1.RabbitmqSource, opts v1.UpdateOptions) (*sourcesv1alpha1.RabbitmqSource, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, rabbitmqSource *sourcesv1alpha1.RabbitmqSource, opts v1.UpdateOptions) (*sourcesv1alpha1.RabbitmqSource, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*sourcesv1alpha1.RabbitmqSource, error)
	List(ctx context.Context, opts v1.ListOptions) (*sourcesv1alpha1.RabbitmqSourceList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *sourcesv1alpha1.RabbitmqSource, err error)
	RabbitmqSourceExpansion
}

// rabbitmqSources implements RabbitmqSourceInterface
type rabbitmqSources struct {
	*gentype.ClientWithList[*sourcesv1alpha1.RabbitmqSource, *sourcesv1alpha1.RabbitmqSourceList]
}

// newRabbitmqSources returns a RabbitmqSources
func newRabbitmqSources(c *SourcesV1alpha1Client, namespace string) *rabbitmqSources {
	return &rabbitmqSources{
		gentype.NewClientWithList[*sourcesv1alpha1.RabbitmqSource, *sourcesv1alpha1.RabbitmqSourceList](
			"rabbitmqsources",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *sourcesv1alpha1.RabbitmqSource { return &sourcesv1alpha1.RabbitmqSource{} },
			func() *sourcesv1alpha1.RabbitmqSourceList { return &sourcesv1alpha1.RabbitmqSourceList{} },
		),
	}
}
