/*
Copyright 2022 The Knative Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
	eventingv1alpha1 "knative.dev/eventing-rabbitmq/pkg/apis/eventing/v1alpha1"
)

// RabbitmqBrokerConfigLister helps list RabbitmqBrokerConfigs.
// All objects returned here must be treated as read-only.
type RabbitmqBrokerConfigLister interface {
	// List lists all RabbitmqBrokerConfigs in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*eventingv1alpha1.RabbitmqBrokerConfig, err error)
	// RabbitmqBrokerConfigs returns an object that can list and get RabbitmqBrokerConfigs.
	RabbitmqBrokerConfigs(namespace string) RabbitmqBrokerConfigNamespaceLister
	RabbitmqBrokerConfigListerExpansion
}

// rabbitmqBrokerConfigLister implements the RabbitmqBrokerConfigLister interface.
type rabbitmqBrokerConfigLister struct {
	listers.ResourceIndexer[*eventingv1alpha1.RabbitmqBrokerConfig]
}

// NewRabbitmqBrokerConfigLister returns a new RabbitmqBrokerConfigLister.
func NewRabbitmqBrokerConfigLister(indexer cache.Indexer) RabbitmqBrokerConfigLister {
	return &rabbitmqBrokerConfigLister{listers.New[*eventingv1alpha1.RabbitmqBrokerConfig](indexer, eventingv1alpha1.Resource("rabbitmqbrokerconfig"))}
}

// RabbitmqBrokerConfigs returns an object that can list and get RabbitmqBrokerConfigs.
func (s *rabbitmqBrokerConfigLister) RabbitmqBrokerConfigs(namespace string) RabbitmqBrokerConfigNamespaceLister {
	return rabbitmqBrokerConfigNamespaceLister{listers.NewNamespaced[*eventingv1alpha1.RabbitmqBrokerConfig](s.ResourceIndexer, namespace)}
}

// RabbitmqBrokerConfigNamespaceLister helps list and get RabbitmqBrokerConfigs.
// All objects returned here must be treated as read-only.
type RabbitmqBrokerConfigNamespaceLister interface {
	// List lists all RabbitmqBrokerConfigs in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*eventingv1alpha1.RabbitmqBrokerConfig, err error)
	// Get retrieves the RabbitmqBrokerConfig from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*eventingv1alpha1.RabbitmqBrokerConfig, error)
	RabbitmqBrokerConfigNamespaceListerExpansion
}

// rabbitmqBrokerConfigNamespaceLister implements the RabbitmqBrokerConfigNamespaceLister
// interface.
type rabbitmqBrokerConfigNamespaceLister struct {
	listers.ResourceIndexer[*eventingv1alpha1.RabbitmqBrokerConfig]
}
